### PR TITLE
refactor tests from unittest to pytest style

### PR DESCRIPTION
**Pull request by bleso-a**

### CODE REVIEW

**Review by rotten — APPROVED** [review]
:100:

**Review by j0monty — CHANGES_REQUESTED** [review]
Travis CI doesn't appear to run unit tests now. 
See: https://app.travis-ci.com/github/mantiumai/mantiumclient-py/jobs/547330740

that 0 tests have been run. You'll likely need to tweak the .travis.yml or setup.py to fix:
https://github.com/mantiumai/mantiumclient-py/blob/main/.travis.yml

**Comment by bleso-a** [comment]
@j0monty I have edited the YAML file to capture the test, and here is the job log. 
https://app.travis-ci.com/github/mantiumai/mantiumclient-py/jobs/547494822

**Review by j0monty — APPROVED** [review]
LGTM

**Pull request merged**
